name: furni_mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  intl: ^0.20.2
  transparent_image: ^2.0.1

  # State management
  flutter_riverpod: ^3.0.3

  # UI widgets
  flutter_carousel_widget: ^2.2.0

  # Maps
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # ğŸ”¥ Shared Preferences for storing JWT and other data
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
